### ISSUE TITLE
responsible party role definition update

### ISSUE THREAD

**Issue by yongqunh** [obi-ontology/obi#1099]
Current definition of 'responsible party role' is: a study personnel role played by a party who is accountable for the execution of a study component and can make decisions about the conduct of the study. A subclass of this role is 'sponsor role', which means that a sponsor can only be a person. 

However, a sponsor can be other than a person. For example, many clinical trials are sponsored by industry company or organization. See the WHO reference:  https://www.who.int/ictrp/network/trds/en/

Requested by: Leon Li, Asiyah Lin, and Oliver He.

**Comment by jamesaoverton** [comment]
1. Although the definition refers to 'study personnel role' that term does not exist in OBI. I think that's an artifact of old edits. Since 'responsible party role' is a subclass of 'investigation agent role', the definition should be "a investigation agent role played by a party who is accountable for the execution of a study component and can make decisions about the conduct of the study." I will update this term (and 'work role' and 'reporting party role') so that they don't refer to the nonexistent 'study personnel role'.

2. Despite the word "personnel", I don't that anything in these definitions is intended to limit these roles to people. The word "party" and "agent" seem deliberately broad enough to include organizations and companies. So I suggest that you go ahead and used these terms.
