### ISSUE TITLE
OBI: organism and BFO: object

### ISSUE THREAD

**Issue by CDowland** [obi-ontology/obi#1108]
Should OBI: organism become a child of BFO: object? I think it should, and I explain why below. 

Organisms are mentioned as examples of objects in the BFO annotations for the object class. Furthermore, in Arp, Smith, and Spear’s Building Ontologies with Basic Formal Ontology (2015), organisms are given as examples of BFO objects. On page 91, they write, “An organism is an object in this sense, as is a single cell, an egg (including all its contents), a space ship (including all its contents), and a planet.”  They reiterate this on the next page (92), writing, “Organisms, which as we saw are objects in the BFO sense…” In the glossary of the book, when defining ‘object,’ they again include ‘an organism’ among the examples given (181).  

It may also be worth noting that OBI: organism appears as a child of BFO: object in the following fifteen ontologies (and perhaps others; I restricted my search to ontobee): Cell Ontology, Cell Line Ontology, Drosophila Phenotype Ontology, The Drug Ontology, Human Phenotype Ontology, Kidney Tissue Atlas Ontology, Mammalian Phenotype Ontology, Ontology of Chinese Medicine for Rheumatism, Ontology of Host Pathogen Interactions, Obstetric and Neonatal Ontology, Ontology of Precision Medicine and Investigation, The Prescription of Drugs Ontology, PRotein Ontology (PRO), Unified phenotype ontology, WBPhenotype.

In sum, BFO: object is clearly intended to include organisms, and several ontologies that use OBI: organism are consistent with that intent by having it as a subclass of BFO: object. OBI could be consistent with that intent as well, and also be consistent with those other ontologies, by doing the same. 

I should note that this is a bit similar to an issue opened in the past  (#https://github.com/obi-ontology/obi/issues/994#issue-406045676), but I think this is different enough to warrant a new discussion.

**Comment by bpeters42** [comment]
Thank you for the detailed writeup. OBI has decided in general to never make the distinctions between BFO:object, object part and object aggregate, because OBI deals (in contrast to many other ontologies) with entities on various different levels of granularity equally. We have found it challenging to talk about atoms in molecules, molecules in cells, cells in organisms etc. using this paradigm, where the same entity could be viewed as an aggregate, a part or an object. More importantly, we have not found any downside to drop this distinction entirely, and rather refer to material entities. This has been a design decision for 10+ years now, so we would be very hesitant to re-open this unless there is clear evidence for negative consequences in terms of logical inferences for this decision.

**Comment by CDowland** [comment]
Thanks for responding so quickly. I appreciate your explaining this so that I can understand the choices that were made.

I can understand why you might wish to avoid the difficulties of deciding which things are objects and which are object aggregates. And while it would be odd to have other classes, but not organism, as children of BFO: object, that oddness is avoided by your approach.
