### ISSUE TITLE
Weird term stanza in obi.obo file

### ISSUE THREAD

**Issue by cmpich** [obi-ontology/obi#1183]
There is a weird term stanza in the current obi.obo file:

[Term]
id: Definition
is_a: IAO:0000102 ! data about an ontology part

Looks like an error to me.

**Comment by jamesaoverton** [comment]
Thanks for the bug report. "Definition" (and "Subset", "Synonym") are part of the "OBO in OWL" namespace: <http://www.geneontology.org/formats/oboInOwl>. I think they're expected in an `.obo` format file. Are they causing a problem for you?

OBI was designed from the beginning in `.owl` format, not `.obo` format, so we strongly recommend using `obi.owl` and not `obi.obo`.

**Comment by cmpich** [comment]
I have never seen those 'terms' in an obo file. Each term stanza has an 'id' line that is the obo ID of the term which always has a prefix and a colon as a namespace identifier.  The OBO parser (in obo.jar) is chocking on those terms.

Also, there are relationship lines in the file such as 
`is_a:`
with no related to entry. The parser also is failing on those lines.

Moving to OWL is not something we can do that quickly.

**Comment by jamesaoverton** [comment]
None of the regular OBI developers work with `.obo` files, which makes it tricky to debug this. To create `obi.obo` we're just using the official OBO-format code from OWLAPI (via ROBOT). Can you please provide a link to the `obo.jar` file that is failing to parse `obi.obo`?

**Comment by cmpich** [comment]
That jar file we have been using for a while now. I don't know where we got it from but here is the contents of the Manifest file:
`Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Created-By: 1.5.0_22-147 (Apple Inc.)
Specification-Title: OBO API
Sealed: true
Specification-Version: 1.000
Specification-Vendor: Open Biological Ontologies
Implementation-Title: org.obo
Implementation-Version: 1.000
Implementation-Vendor: Berkeley Bioinfomatics and Ontologies Project

`

**Comment by cmpich** [comment]
I have never seen such terms / term stanzas in an obo file. Shouldn't they have at least a prefix? What ontology do they come from? The obo format also describes IDs as namespace + UID.

**Comment by jamesaoverton** [comment]
Thanks for sending that information about `obo.jar`, but I can’t determine the source of that code.

The terms come from the OBO in OWL ontology, linked above, which supports the expression of OBO format in OWL. I also find it strange that these Di t have prefixes.

@cmungall can you point us in the right direction?

**Comment by cmungall** [comment]
Hi Christian and James

More later but the solution here is straightforward. obi.owl contains the following:

```
    <!-- http://www.geneontology.org/formats/oboInOwl#Definition -->

    <owl:Class rdf:about="http://www.geneontology.org/formats/oboInOwl#Definition">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000102"/>
    </owl:Class>
``` 

This is confusing regardless of what format is rendered in. This class doesn't seem to do any work, so this can be removed safely. 

(oio:Definition is a syntactic feature of obo and shouldn't have axioms injected on it just the same as for owl constructs)

btw @cmpich I'm guessing you are using a deprecated oboedit codebase

**Comment by cmungall** [comment]
obo format is ubiquitous in bioinformatics. I think it's counterproductive to push people to using owl. owl is great for managing ontologies, but it's not an appropriate level of abstraction for a lot of applications, and language support is very poor outside the jvm. I suspect there are many groups that could be using obi that aren't because they have difficulty loading it into their databases or integrating it into the their toolchains.

A modern JSON serialization with an obo-like level of abstraction is a good target for people, I recommend OBI publish an obi.json, robot supports this, more rationale here:
https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

@cmpich already uses this json in the context of the alliance.

But this isn't a panacea. Many groups implement strict constraints on what gets loaded with an ontology, and things like the unusual Definition is_a definition axiom. This can break things (or at least confuse end-users) regardless of the serialization.

We need better well-defined structural profiles along the lines of https://owlcollab.github.io/oboformat/doc/obo-syntax.html#6 this could be defined in ShEx and enforced by robot, I think this will help users a lot if there is a clear profile that conforms to their implicit requirements, we will get there.

**Comment by jamesaoverton** [comment]
@cmpich I removed more OIO terms from the OBO-format output. Can you please check this file?

https://github.com/obi-ontology/obi/blob/dd17b4a8f8f048f726c0d18a612c3cbc91696b41/views/obi.obo?raw=true

**Comment by jamesaoverton** [comment]
@cmpich Does my PR fix the problem?

**Comment by jamesaoverton** [comment]
I'll assume that it's fixed and merge the PR. Please reopen if you still have problems.

**Comment by cmpich** [comment]
Yes, the weird stanza lines are gone. Thank you.
But what about the empty is_a lines?
