### ISSUE TITLE
Reserve OBI ID range for assays being modelled by the PennTURBO team

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1204]
Hi, @jamesaoverton 

One of our sources for defiening assays is LOINC, which has 93,601 tests, in both "clinical" and "lab" categories. It's pretty unlikely that we will semantically model all of those, but we should leave space for modelling assays from other sources, too.

Could we please reserve OBI:3000000 - OBI:3020000, or something similar?

**Comment by jamesaoverton** [comment]
I don't see any other terms using `OBI:3*`, so that's fine. You should keep using those and we'll figure out a way to mark them as reserved.

I would like to do a little more research into how other projects handle this. Here are two examples:

- Relation Ontology https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-idranges.owl
- Cell Ontology https://github.com/obophenotype/cell-ontology/blob/master/src/ontology/cl-idranges.owl

It looks like those both come from an ODK template:

https://github.com/INCATools/ontology-development-kit/blob/master/template/_dynamic_files.jinja2#L92

@matentzn Beyond that ODK template, do you know of any tooling supporting idranges?

**Comment by jamesaoverton** [comment]
Historical note: OBI doesn't currently have any idrange restrictions. We just try to use the next available ID, and recently started using this OBI Term ID Reservations sheet:

https://docs.google.com/spreadsheets/d/1tpDrSiO1DlEqkvZjrDSJrMm7OvH9GletljaR-SDeMTI/edit?usp=drive_web&ouid=114329883251282963390

In the early days of OBI there were different working groups that had their own ranges, and you can see that OBI IDs are not all consecutive. There might be some records about that in the legacy repo, but I don't have time to dig for them:

https://github.com/obi-ontology/obi-legacy-svn

**Comment by matentzn** [comment]
There is afaik know currently no computational use of the idranges files. I think they were invented with the hope that Protege could pick them up to configure id ranges automatically, but now they are just documentation, at least for now (@cmungall correct me if I am wrong). So now we just have it a requirement that if you want to commit terms, you have to have an idrange first, so you ask for it, we modify idranges.owl and then people can start editing. I dont even think ODK does anything with that file (other than making it)!

**Comment by jamesaoverton** [comment]
Thanks @matentzn, that's what I thought.

So I would propose creating a `src/ontology/obi-idrange.owl` file, following that pattern, and assigning blocks for:

1. the OBI Term ID Reservation sheet
2. this LOINC work

I'm not sure it's worthwhile to do the archaeology on the weird ranges that have already been used.

**Comment by cstoeckert** [comment]
I think we are set with this for TURBO work. Note: not doing LOINC work - taking an alternate approach based on Penn EHR lab tests and results.
