### ISSUE TITLE
NTR: Capture Hi-C

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1251]
Hello, ENCODE would like to request a NTR for a new type of assay we will be supporting.

**editor preferred term:** Capture Hi-C
**alternate terms:** cHi-C
**textual definition:** Capture Hi-C is a type of Hi-C assay in which a selection step is performed on ligated fragments in order to enrich for ligation products containing specific regions of interest.
**definition source for the textual definition:** https://pubmed.ncbi.nlm.nih.gov/29979818/
**logical definition:** subclass of Hi-C assay (OBI:0002440)

**Comment by jamesaoverton** [comment]
Discussed on 2021-01-25: This looks good. We'd like to add an example from the cited PubMed paper: "PMID:29979818 Chromosome conformation capture (3C), coupled with next-generation sequencing (Hi-C), provides a means for deciphering not only the principles underlying genome folding and architecture, but more broadly, the role 3D chromatin structure plays in gene regulation and the replication and repair of DNA."

@bonitalam You've submitted a number of excellent term requests. We're often slow in responding to them, because OBI does not have any direct funding. Would you, or someone from your team, be interested in joining the weekly OBI calls, and contributing terms directly to OBI?

**Comment by jamesaoverton** [comment]
Sorry, didn't mean to close.

**Comment by bonitalam** [comment]
@jamesaoverton sure, I could potentially join the calls if I have no scheduling conflicts with existing calls. I'd be happy to contribute terms directly. Are the calls weekly Monday at 9am PST?

**Comment by jamesaoverton** [comment]
Yes, that's the right time. The call details are at the bottom of this page: http://obi-ontology.org/

Most OBI terms are specified in tables in [`src/ontology/templates/`](src/ontology/templates/). To add your term to OBI I just added a row to [`src/ontology/templates/assays.tsv`](src/ontology/templates/assays.tsv) and made a Pull Request: #1287. If you can add your own terms to the templates, then it saves our volunteers precious time, and help to get your terms in faster.

Our [README](https://github.com/obi-ontology/obi/blob/master/README.md) has more detail. I've been running a public [office hour](https://calendar.google.com/event?action=TEMPLATE&tmeid=MnNmamQybnUxcDAyaTk2aW1ybDRiZmFkaWRfMjAyMTAyMDFUMTYwMDAwWiBxbzIzZDc0OWJqOHRkbDBvZWU2dGF2cGhzc0Bn&tmsrc=qo23d749bj8tdl0oee6tavphss%40group.calendar.google.com&scp=ALL) every Monday before the OBI call, where you can ask technical questions. And if neither of those is helpful, we could arrange a call between you and an OBI developer.

Thanks again for your valuable contributions to OBI!

**Comment by bonitalam** [comment]
Thanks for the information @jamesaoverton. I will take a look at the links and plan to join next week's call.
