### ISSUE TITLE
questions about "induced mutation"

### ISSUE THREAD

**Issue by sbello** [obi-ontology/obi#1366]
The Alliance for Genomic Resources is reviewing OBI terms under the "genetic transformation" branch as we would like to use these to represent the generation methods for our Allele objects. As part of this we have a few questions about the OBI term "induced mutation" (OBI:0001154)

Term label - The label for this term seems to represent the end product rather than the process. Would it be possible to change the label to "induced mutagenesis" to clarify that this is the process of creating the mutation and not the mutation itself?

Definition - The current definition is "a genetic transformation that the modification of the genetic material (either coding or non-coding) of an organism is caused by mutagenic compounds or irradiation". The specification of "mutagenic compound or irradiation" could be interpreted as meaning that only those methods should fall under this term. We would like to use this term in a broader sense to cover all methods of induced mutagenesis. For example we are developing terms for targeted mutagenesis, and endonuclease mediated mutagenesis that we would like to place under this term. Is the phrase "mutagenic compound" meant to be interpreted that broadly? Based on the placement of "site directed mutagenesis" (OBI:0002619) under this term we are guessing it is but it would be helpful to clarify this in the definition.

 Additional tickets with other questions and new term request will be coming soon. Is there anything specific you would like in the new term requests? If you ping me on the obo community slack I can share with you the spreadsheet we've been using to collect and define our term requests. These aren't ready for submission just yet but if we are missing any vital information it would be good to know.

Thanks,
Sue Bello

**Comment by cstoeckert** [comment]
Hi Sue, thank you for the proposed improvements.
Agree with changing the label. 
Also agree that the definition should allow for targeted mutagenesis and endonuclease mediated mutagenesis. Instead of 'mutagenic compounds', would 'mutagenic materials' be broad enough? Is there a better wording that you can propose?

For new term requests, please see http://obi-ontology.org/page/OBI_term_guidelines but also look at the templates here:  https://github.com/obi-ontology/obi/tree/master/src/ontology/templates to see the patterns we are using for assays, devices, etc. in case any of your terms fit and there are axioms that are appropriate. 
Thanks! Chris

**Comment by sbello** [comment]
Would this work?
"A genetic transformation that is the modification of the genetic material (either coding or non-coding) of an organism caused by mutagenic processes, compounds, or irradiation".

**Comment by cstoeckert** [comment]
Sounds good to me!
