### ISSUE TITLE
CFDE NTRs for HuBMAP project

### ISSUE THREAD

**Issue by mgiglio99** [obi-ontology/obi#1393]
Hello,
We are working on Batch 2 of term requests as part of the CFDE project. This set is needed by the HuBMAP project.
Here is a list of the terms with draft definitions, parentage, etc.
https://docs.google.com/spreadsheets/d/1_XaxKYQKO0nnH8yY8zwz_lhkweuUsO0ARyF22PI1uTk/edit?usp=sharing
We are working on finalizing them, but I feel the terms are far enough along to reserve OBI term ids.
Please take a look and see if you agree that they are in scope for OBI and that it would be ok to register OBI ids for them at this stage.
Thanks,
Michelle and @nsuvarnaiari

**Comment by hectorguzor** [comment]
Hi @mgiglio99,

here is the definition for 'detection technique' I showed in the OBI call on  7/26/21.

Detection technique =(def) Assay **D** counts as a detection technique in assay **A** if and only if 

(I) In generating information _ia_ about target _ta_  of **A**, one utilizes **D** to generate information _id_ about a proxy _td_, where _id_ is the target of **D** and _id_ is used to determine what a measurement of _ia_ would be. And 

(II) _td_ and _ta_ are disjoint. 

in looking at the terms you requested:

1. what you have for row 10 as a detection technique seems fine to me. It is the fluorescence detection assay that detects the fluorescently labeled molecules to get at localizing specific DNA or RNA sequences. 
2. Row 7 doesn't have a textual definition, but I would imagine (given the label) that identifying an antibody for imaging will be done in virtue of detecting fluorescence. 
3. Row 4 is an interesting case. Because the parent for "autofluorescence microscopy assay" is "autofluorescence microscopy assay" (which has as a parent "fluorescence detection assay"). My intuition is to leave "detection technique" empty here. Because while a microscope is used to produce a magnified image of the object, I'm assuming the object is still detected via a fluorescence detection assay. (but I could be wrong).
4. for row 18 I am also not sure. This may be fine. sometimes it seems to me that mass spectrometry assays are detection techniques and other times not. I'm not sure what to think in this case. It seems to work here. 

I hope this helps

**Comment by mgiglio99** [comment]
Thanks for this Hector - I'll take a look at these more closely - this is great input as we are still working on developing these.
Another set that we've already done the pull request for and that we feel are ready to and that we'd like to get your input on are in https://github.com/obi-ontology/obi/issues/1243
Could you take a look at those ?
Thanks,
Michelle

**Comment by mgiglio99** [comment]
Discussed on Nov. 1 call - 
CHMO term has been adopted by OBI for long term care, therefore it’s in the assay template and we can change it as needed. We will add equivalence axioms to it and then use it as an inferred parent of our new ‘autofluorescence microscopy’ term.

**Comment by mgiglio99** [comment]
Suvvi and I think that all of the remaining questions for this batch of NTRs have been resolved.
Here is the final spreadsheet for review:
https://docs.google.com/spreadsheets/d/1_XaxKYQKO0nnH8yY8zwz_lhkweuUsO0ARyF22PI1uTk/edit?usp=sharing
We hope to finalize these at the next OBI call.

**Comment by nsuvarnaiari** [comment]
Hi @hectorguzor 

We would like to change the label for "fluorescence microscopy" (CHMO:0000087) to "fluorescence microscopy assay" . @jamesaoverton gave us an "ok" for this change, so went ahead and revised the name in the google doc below.

Could you please check the equivalence axiom for "fluorescence microscopy assay" in the google doc - [https://docs.google.com/spreadsheets/d/1_XaxKYQKO0nnH8yY8zwz_lhkweuUsO0ARyF22PI1uTk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1_XaxKYQKO0nnH8yY8zwz_lhkweuUsO0ARyF22PI1uTk/edit?usp=sharing)

"fluorescence microscopy" is a child of "microscopy assay" (OBI:0002119) and we want to add "fluorescence detection assay" (OBI:0001501) an inferred parent. 

Also, please take a look at other terms which are complete and ready for submission. If everything looks good, we will go ahead with a PR.

Thanks,
Suvvi

**Comment by hectorguzor** [comment]
Hi @nsuvarnaiari 

- adding '('material entity' and ('bearer of' some fluorescence))' to the input column of 'fluorescence microscopy' gets you 'fluorescence detection assay' as an inferred parent.
- 'fluorescence detection assay' can be removed from the detection technique column since it is an inferred parent 'fluorescence microscopy' wouldn't need to have it as a part. 
- 'microscope' can be removed from the devise column. It already inherits this from 'microscopy assay'

Yes, I will take a look at the other terms so we can put this on the OBI agenda for 2021-11-22 to get that PR going.
Hector

**Comment by hectorguzor** [comment]
Hi @nsuvarnaiari 
I got a chance to look at the other assays.

- For 'autofluorescence microscopy assay' (row 5) you don't need '('material entity' and ('bearer of' some fluorescence))' because it is already a type of 'fluorescence detection assay'.

- For 'fluorescence in-situ hybridization assay' (row 11) OBI has [chromosome organization assay by fluorescence in-situ hybridization](http://purl.obolibrary.org/obo/OBI_0001683) and this has 'FISH' as an alternative term. Are these the same?

Everything else looks good to me. Let me know if you have any questions.

**Comment by hectorguzor** [comment]
Discussed on OBI call 2021-11-22: There was concern that making 'fluorescence microscopy an equivalence class that has ('material entity' and ('bearer of' some fluorescence)) would unintentionally infer children of 'fluorescence microscopy' into 'fluorescence detection assay'. Hector will check in protege to make sure this is not the case. It was also suggested to make 'light microscopy' the asserted parent of 'fluorescence microscopy'.

**Comment by hectorguzor** [comment]
Getting 'fluorescence detection assay' as an inferred parent for 'fluorescence microscopy' was possible by making the 'logical type' a 'subclass' (if making it 'equivalent' is a concern). Here is what it looks like

<img width="515" alt="fluro-micro" src="https://user-images.githubusercontent.com/78870607/142950731-7381e2c6-8d3f-4ac9-b506-f76b480e8f4d.png">

Using `robot diff`, I checked that adding ('material entity' and ('bearer of' some fluorescence)) did not generate any weird inferences. Everything looks good. This is all I got with the diff report. 

<img width="806" alt="F-M" src="https://user-images.githubusercontent.com/78870607/142950659-47e216d8-4748-425b-b6de-272fdb92e456.png">

I made 'light microscopy' the asserted parent as discussed in OBI call 2021-11-22. 'fluorescence microscopy' got inferred as a child of 'fluorescence detection assay'. You don't get, for example, 'widefield microscopy'  as a child of  'fluorescence detection assay' (I believe that was the concern).

**Comment by nsuvarnaiari** [comment]
Hi @cstoeckert , @bpeters42 and @hectorguzor 

Thanks Hector for checking the equivalence axiom for 'fluorescence microscopy'. Glad everything is looking good. If nobody has any other concerns we will go ahead with the pull request.

Thanks,
Suvvi and Michelle

**Comment by ddooley** [comment]
Approved for pull request step.

**Comment by nsuvarnaiari** [comment]
Michelle and I made another change in the template after going over Hector's comment from Nov 19th.

Currently, the ontology has [chromosome organization assay by fluorescence in-situ hybridization](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001683&viewMode=All&siblings=false) a child of [in-situ hybridization assay](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001686&viewMode=All&siblings=false), but we are proposing it to be a child of 'fluorescence in-situ hybridization assay' instead, a new term in the template (row 11). We are also proposing "FISH" to be an alternate term for 'fluorescence in-situ hybridization assay' but not [chromosome organization assay by fluorescence in-situ hybridization](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001683&viewMode=All&siblings=false).

Template:
 https://docs.google.com/spreadsheets/d/1_XaxKYQKO0nnH8yY8zwz_lhkweuUsO0ARyF22PI1uTk/edit?usp=sharing

Hope this edit is making sense.
Thanks,
Suvvi

**Comment by hectorguzor** [comment]
Hi @mgiglio99, I believe this issue has been resolved. If it has not, we can reopen it. But I will go ahead and close it for now.
