### ISSUE TITLE
NTR: data items - specimen storage

### ISSUE THREAD

**Issue by cmrn-rhi** [obi-ontology/obi#1577]
**Specimen Storage Terms**
- ROBOT table new term requests (basic template, data item specific template unavailable at this time)
- Terms with _tan_ labels have already undergone an initial OBI review but need final review and to be entered into OBI.
- `GenEpiO ID (temporary)` and `Curation Notes` annotations are for curation work and should be removed prior to ROBOT integration.

ROBOT table URL ("data" tab): https://docs.google.com/spreadsheets/d/1SiVgFDy9jOoFIhywvLjYLMBLqJsZ0B9An9170RYpQRM/edit#gid=2146269079&range=A3

ontology ID | label
-- | --
OBI:0002863 | specimen storage duration
OBI:0002864 | specimen storage temperature
OBI:0002865 | specimen storage location

**Comment by cmrn-rhi** [comment]
@ddooley

**Comment by cstoeckert** [comment]
Started discussing on OBI Oct. 3, 2022 call. Question of whether these belong in OBIB (ontology for biobanking) rather than OBI. OBIB covers administration and management of biobanks so these may relate more to that aspect. Also these are pre-composed terms and raises question of how much pre-composition OBI wants to include.

**Comment by ddooley** [comment]
@zhengj2007 says OBIB will take these on!  Damion will switch request over to there.

**Comment by ddooley** [comment]
Now handled in OBIB https://github.com/biobanking/biobanking/issues/102.
