### ISSUE TITLE
NTR: long-read RNA sequencing assay

### ISSUE THREAD

**Issue by jenjou** [obi-ontology/obi#1780]
Preferred Term: long-read RNA sequencing assay
Synonyms: long-read RNA-seq
Definition: An assay that determines the sequence of an RNA molecule using single-molecule technologies to allow longer read lengths.
Relevant info: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6824406/
Parent Term: OBI:0001177 (RNA sequencing assay)

This term is similar to OBI:0002575 (isoform sequencing), but that term appears to be PacBio specific and wouldn't be appropriate for other technologies, such as the Oxford Nanopore long read methods. This term could potentially be a parent of OBI:0002575.

**Comment by bpeters42** [comment]
Thank you for the submission. We are struggling a bit with the use of 'long-read' in the term name, as what is considered 'long' has been changing over time. Is there a different criteria we can use? Something like 'pore based sequencing' ? 'single molecule based sequencing' ? Or we just use the branded names as children of 'RNA sequencing (e.g. PacBio single molecule sequencing; Oxford Nanopore sequencing' ? Just suggestions, and all come with other problems (like companies changing names). So any input would be very valuable from you!

**Comment by jenjou** [comment]
I am also reaching out for more information and will add more comments if I have anything to share.
One definition I was given was that the reads should be "an average of 600 bp or longer", but I'm asking for some kind of publication references for this. I did see that 600bp is near the median read length reported here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7768885/

**Comment by bpeters42** [comment]
Thank you for getting more information on this. But to be clear, I think that any length cutoff is potentially problematic - unless we make it explicit in the term name. Older versions of PacBio didn't routinely achieve 600 bp read lengths - so would that be considered 'short read length sequencing' ? We have a recurring issues that for technology (not biology), emphasis on 'long', 'high', 'massive', 'large' etc. become outdated after a decade or two. No one would consider my PC from 20 years ago to be a 'high speed computer' today. So it seems better to be quantitative rather than qualitative, and signal that in the term name. OR we focus on what makes the 'long read' technologies different, which as I think I understand it is reading from single molecules without an amplification step. 

All not easy, and thank you for helping getting these in!

**Comment by turbomam** [comment]
Discussing in 2024-04-22 OBI call.
- Is this inherently sequencing of a single molecule? **Direct** sequencing of a RNA molecule? (As opposed to sequencing of cDNA?)

We also  have alternative term and comments annotations for adding elaborative (but not definitional) content. 

How about "Single molecule direct RNA sequencing assay?"

**Comment by bpeters42** [comment]
Hi @jenjou - did you get any more inputs / did you see the suggestion on focusing on single molecule sequencing?

**Comment by jenjou** [comment]
Hi, thank you for the reminder! I am still waiting to hear back from a lab which is using the Nanopore direct RNA/DNA sequencing method to see what term makes sense for them. I will try to remind them as well and update here as soon as possible.

Based on some discussion that has happened so far, it does seem like my original request for "long-read RNA sequencing assay" might not be needed. But we would still want something in its place.

**Comment by jenjou** [comment]
Hello, just wanted to update this ticket. I don't think we are going to need a term like this (or alternative for it) for now, so I will close my request.
