### ISSUE TITLE
mouth rinse wash specimen

### ISSUE THREAD

**Issue by masciam** [obi-ontology/obi#1803]
I got the following request in the OBIB from wverhoef 
Hi Anna Maria,
Thanks so much for replying! We are leveraging OBIB for biospecimen types and looking for a term for "Mouth Rinse" and we found an NCIt concept in Ontobee which represents the semantic we are seeking (see below), but we are wondering if there is an OBIB concept to match.
Mouth Rinse Biospecimen Type, https://ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C198712, defined as "A sample consisting of biological material from the buccal cavity. A collection solution is introduced into the mouth, swished around, and then collected."
Since the specimen in OBIB are imported from OBI I think this request is for OBI. Can you add the term under specimen from organism?

**Comment by mgiglio99** [comment]
Discussed on 7/29 call
Adding this term sounds good. We have a question for you - do you agree that "lavage" is a term that could be used instead of "rinse"?  There are other lavage terms already in OBI and according to the OBI def for lavage process it sounds the same as the rinse process.
In the process of looking at this one, we realized that some 'specimen from organism' terms are not placed correctly, so we'll need to review that. (Possible intern project.)
We also feel that having a general parent term for 'lavage specimen' makes sense. This would be analogous to 'swab specimen'

**Comment by masciam** [comment]
Michelle,
mouth lavage is ok and I suppose moth rinse will be a synonym right?
Thanks
AM

**Comment by mgiglio99** [comment]
Hi,
That's what we were thinking, yes.
Michelle
