### ISSUE TITLE
NTR: PacBio Sequel Sequencing Platform

### ISSUE THREAD

**Issue by carrieadavis** [obi-ontology/obi#849]
Project: ENCODE

Pacific Bioscience has come out with an new sequencing machine, the Sequel to complement their RS II machine already registered in OBI: http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0002012.

NTR: "PacBio Sequel"

* Editor preferred term: "PacBio Sequel"
* Alternative terms: Pacific BioSciences Sequel
* Textual definition: A DNA sequencer which is manufactured by the Pacific Biosciences corporation. Built upon single molecule real-time sequencing technology, the machine is optimized for generation with long reads and high consensus accuracy.
* Definition source for the textual definition: http://www.pacb.com/products-and-services/pacbio-systems/sequel/
* Logical definition (or parent term):
* Example of usage:  The cDNAs were sequenced on the PacBio Sequel platform.
* Term editor: Carrie A Davis

**Comment by bonitalam** [comment]
Since Pacific Biosciences sequencing platforms are becoming more widely used, I would like to bring up this NTR along with adding a new NTR for the newest PacBio sequencer model. The ENCODE project would like to distinguish files generated by the different sequencing platform models. 

NTR: "PacBio Sequel II"

- Editor preferred term: "PacBio Sequel II"
- Alternative terms: Pacific BioSciences Sequel II
- Textual definition: A DNA sequencer which is manufactured by the Pacific Biosciences corporation. Built upon single molecule real-time sequencing technology, the machine is optimized for generation of highly accurate long reads (HiFi reads).
- Definition source for the textual definition: http://www.pacb.com/products-and-services/sequel-system/latest-system-release/
- Logical definition (or parent term):
- Example of usage: Kingan, S. B., Urban, J., Lambert, C. C., Baybayan, P., Childers, A. K., Coates, B., … Geib, S. M. (2019). A High-Quality Genome Assembly from a Single, Field-collected Spotted Lanternfly (_Lycorma delicatula_) using the PacBio Sequel II System. GigaScience (2019). PMID: 31609423  
- Term editor: Bonita Lam

**Comment by DanBerrios** [comment]
Consider a subclass under DNA Sequencer for "long-read DNA Sequencers" or similar class.

**Comment by DanBerrios** [comment]
Textual definition: A DNA sequencer built upon single molecule real-time sequencing technology,  optimized for generation of highly accurate long reads (HiFi reads), and which is manufactured by the Pacific Biosciences corporation.  Perhaps delineate the distinguishing features of this particular model better.

**Comment by DanBerrios** [comment]
@bonitalam Bonita: Can you define a bit more "hifi reads"...are there criteria for hifi?  Thanks.

**Comment by bonitalam** [comment]
@DanBerrios PacBio defines HiFi reads as read lengths of 10-20 kb with average sequence identity greater than 99% from raw single molecule reads. 

Source: https://www.pacb.com/proceedings/single-molecule-high-fidelity-hifi-sequencing-with-10-kb-libraries/

**Comment by DanBerrios** [comment]
@bonitalam Thanks!  Question is: did they get to drink any of their samples?  :-)

**Comment by bonitalam** [comment]
@DanBerrios I hope so since California has some of the best cabs out there. :p

**Comment by bonitalam** [comment]
Hello, I know this ticket was closed. I just wanted to double check, because I am not able to see the platforms when searching for the new terms, OBI:0002632 and OBI:002633. Thanks!
